name: Continuous Integration
 
on:
  pull_request:
    branches:
      - master
 
jobs:
  automation-test-job:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          standalone: true
          dest: ~/setup-pnpm
      - name: pnpm install and test
        run: |
          pnpm install
          pnpm run ci:test